/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:new_Pulley:887002:
  noLoop();
 
  float yVal = iterationOrder[arrayIteration % iterationOrder.length];
  
  pulleys.add(new Pulley(width - 200 + xShift*round/3, yVal)); //Add it to the Items collection, which will be used for: # of items on screen, for-loop draw(),
  arrayIteration++;
  round++;
  
  redraw();
  loop();
} //_CODE_:new_Pulley:887002:

public void slider1_change1(GSlider source, GEvent event) { //_CODE_:changeWeight:625856:
  weight.newtons = changeWeight.getValueI();
} //_CODE_:changeWeight:625856:

public void button1_click2(GButton source, GEvent event) { //_CODE_:reset:948121:
  reset();
} //_CODE_:reset:948121:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  new_Pulley = new GButton(this, 1450, 200, 100, 50);
  new_Pulley.setText("PULLEY");
  new_Pulley.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  new_Pulley.addEventHandler(this, "button1_click1");
  changeWeight = new GSlider(this, 1400, 322, 200, 50, 10.0);
  changeWeight.setShowValue(true);
  changeWeight.setShowLimits(true);
  changeWeight.setLimits(50, 0, 100);
  changeWeight.setNumberFormat(G4P.INTEGER, 0);
  changeWeight.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  changeWeight.setOpaque(true);
  changeWeight.addEventHandler(this, "slider1_change1");
  reset = new GButton(this, 1450, 433, 100, 50);
  reset.setText("RESET");
  reset.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  reset.addEventHandler(this, "button1_click2");
}

// Variable declarations 
// autogenerated do not edit
GButton new_Pulley; 
GSlider changeWeight; 
GButton reset; 
